### ISSUE TITLE
Documentar todo o processo de publicação do app na Google Play e Apple Store

### ISSUE THREAD

**Issue by pedroeagle** [GCES-Escola-em-Casa-2020-2/wiki#6]
O processo de publicação do app utilizando serviço de VPN para redirecionamento das faturas advindas do uso não é tão trivial. Documentar o processo de publicação na Google Play.

Tarefas:
- [x] Reunir com a Carla para direcionamento de como foi feito o processo
- [x] Documentar a reunião com a Carla na documentação final
- [x] Pesquisar o que estiver faltando para concluir o processo
- [x] Documentar na wiki
- [x] Abrir PR no repositório oficial

Checklist:
- [x] Reunir com a Carla para direcionamento de como foi feito o processo
- [x] Documentar a reunião com a Carla na documentação final
- [x] Pesquisar o que estiver faltando para concluir o processo
- [x] Documentar na wiki
- [x] Abrir PR no repositório oficial

**Comment by GeiseSaunier** [comment]
Ainda estou pesquisando sobre a LGPD ao usar VPN. Encontrei muitos sites que comentam sobre, mas estou filtrando o que for mais seguro.
